import { cookies } from "next/headers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AdminSidebar } from "@/components/ui/AdminSidebar";
import AdminNavbar from "@/components/Navbar/AdminNavbar";
import AuthProvider from "@/context";
import { Providers } from "../provider";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Access cookies using next/headers
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value;
  // eslint-disable-next-line react-hooks/rules-of-hooks

  if (!accessToken) {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthProvider>
            <AdminNavbar />
            <SidebarProvider>
              <SidebarInset>
                <AdminSidebar />
                {children}
              </SidebarInset>
            </SidebarProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
