import type { Metadata } from "next";
import "../../styles/globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Providers } from "../provider";
import { AdminSidebar } from "@/components/ui/AdminSidebar";
import AdminNavbar from "@/components/Navbar/AdminNavbar";
import AuthProvider from "@/context";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value;

  // Redirect to login if no access token
  if (!accessToken) {
    redirect("/login");
  }
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <AuthProvider>
          <Providers>
            {/* Main container for the layout */}
            <div className="">
              {/* Sidebar */}

              <SidebarProvider>
                <AdminSidebar />
                <SidebarInset>
                  <AdminNavbar />
                  <main>{children}</main>
                </SidebarInset>
              </SidebarProvider>
            </div>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
